@setlocal
@echo off
setlocal ENABLEDELAYEDEXPANSION

echo Uninstalling Tailviewer...

set INSTALLATION_PATH=%~dp0
if %INSTALLATION_PATH:~-1%==\ set INSTALLATION_PATH=%INSTALLATION_PATH:~0,-1%

set TAILVIEWER_SETUP=tailviewer-setup.exe
set SRC_INSTALLATION_EXECUTABLE=%INSTALLATION_PATH%\%TAILVIEWER_SETUP%
set DEST_INSTALLATION_EXECUTABLE=%TEMP%\%TAILVIEWER_SETUP%
echo %INSTALLATION_PATH%

echo Copying installer %SRC_INSTALLATION_EXECUTABLE% to temporary location %DEST_INSTALLATION_EXECUTABLE%
copy "%SRC_INSTALLATION_EXECUTABLE%" "%DEST_INSTALLATION_EXECUTABLE%" || goto :UNINSTALL_ERROR

echo Deleting installer %SRC_INSTALLATION_EXECUTABLE%
del /Q "%SRC_INSTALLATION_EXECUTABLE%"

echo Uninstalling tailviewer
"%DEST_INSTALLATION_EXECUTABLE%" uninstall "%INSTALLATION_PATH%" || goto :UNINSTALL_ERROR

echo Deleting temporary installer %DEST_INSTALLATION_EXECUTABLE%
del /Q "%DEST_INSTALLATION_EXECUTABLE%"

goto :UNINSTALL_SUCCESS

:UNINSTALL_SUCCESS
echo Uninstalling tailviewer succeeded
exit /b 0

:UNINSTALL_ERROR
echo An error occured during uninstallation
exit /b -1

endlocal